server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.12.67.46:3306/lhf_sso?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: test
    password: Pass@word!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379

jwt_sign_key: 123456


